name:                network-remote
version:             0.1.0.0
github:              "MechDancer/network-remote"
license:             BSD3
author:              "MechDancer"
maintainer:          "berberman, xxczxp"
copyright:           "2019 MechDancer"

extra-source-files:
- README.md
- ChangeLog.md
- cbits/mask.h

description:         Please see the README on GitHub at <https://github.com/MechDancer/network-remote#readme>

dependencies:
- base >= 4.7 && < 5
- network
- network-multicast
- text
- bytestring
- text-latin1
- containers
- time
- io-streams
- network-info
- array
- hashtables
- hashable
- mtl
- transformers
- utf8-string

library:
  source-dirs: src
  include-dirs: cbits
  cc-options: -Wall -std=c99
  when:
    - condition: os(windows)
      then:
        c-sources: cbits/mask-windows.c
        extra-libraries: iphlpapi
      else:
        c-sources: cbits/mask-unix.c

tests:
  network-remote-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - network-remote
    - parsec
    - cereal
